"""Entry point for TaskFlow — wire the services together here."""

# from storage_service import ...
# from notification_service import ...
# from api_service import ...
# from infrastructure import ...

if __name__ == '__main__':
    print('Hello from TaskFlow')
